/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 if the Django process is alive and able to respond. Used by load balancer health checks and CD smoke tests.
         */
        get: operations["api_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates an active user with the given email and password. Does not log the user in — issue a POST /api/auth/login/ next. Rate-limited to 5 requests per minute per IP.
         */
        post: operations["api_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with email and password
         * @description Verifies credentials and sets HttpOnly access/refresh cookies. Access cookie is scoped to /, refresh cookie is scoped to /api/auth/. Rate-limited to 10 requests per minute per IP.
         */
        post: operations["api_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout and clear cookies
         * @description Blacklists the current refresh token and clears both auth cookies. Requires a valid access cookie.
         */
        post: operations["api_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate access and refresh tokens
         * @description Reads the refresh cookie, blacklists it, and issues a new access/refresh pair as HttpOnly cookies. Replay of a used refresh token returns 401.
         */
        post: operations["api_auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current user
         * @description Returns the authenticated user's id and email.
         */
        get: operations["api_auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the current user
         * @description Patch the authenticated user. Email is the only mutable field for now.
         */
        patch: operations["api_auth_me_partial_update"];
        trace?: never;
    };
    "/api/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a public user
         * @description Public profile data for the given user id.
         */
        get: operations["api_users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List posts by user
         * @description Public — published posts for the given user id.
         */
        get: operations["api_users_posts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List posts
         * @description Cursor-paginated feed of published posts, newest first.
         */
        get: operations["api_posts_list"];
        put?: never;
        /**
         * Create a post
         * @description Creates a post and attaches the listed media (which must belong to the caller and have status='ready'). Media must have been uploaded via /api/posts/upload-url/.
         */
        post: operations["api_posts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/upload-url/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a presigned S3 upload URL
         * @description Validates intended content type and size, creates a pending PostMedia row, and returns a short-lived presigned PUT URL. Client must PUT the file with the exact Content-Type and Content-Length they passed here. After upload, an S3 event triggers the cut_image Lambda which posts back to /internal/media/<id>/processed/.
         */
        post: operations["api_posts_upload_url_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/media/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get media status
         * @description Owner-only poll for upload/resize status.
         */
        get: operations["api_posts_media_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a post
         * @description Public.
         */
        get: operations["api_posts_retrieve"];
        put: operations["api_posts_update"];
        post?: never;
        /**
         * Delete a post
         * @description Owner only.
         */
        delete: operations["api_posts_destroy"];
        options?: never;
        head?: never;
        /**
         * Update a post
         * @description Owner only. Caption/price.
         */
        patch: operations["api_posts_partial_update"];
        trace?: never;
    };
    "/api/cart/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current cart
         * @description Returns (or creates) the cart for the authenticated user.
         */
        get: operations["api_cart_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add an item to the cart
         * @description Adds the given post to the cart. If the post is already in the cart, the qty is incremented by the supplied amount (default 1). Posts without a price cannot be added.
         */
        post: operations["api_cart_items_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/items/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove an item from the cart
         * @description Owner only.
         */
        delete: operations["api_cart_items_destroy"];
        options?: never;
        head?: never;
        /**
         * Update cart item qty (absolute)
         * @description Sets the item's qty to the value in the body.
         */
        patch: operations["api_cart_items_partial_update"];
        trace?: never;
    };
    "/api/orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my orders
         * @description Cursor-paginated history of the caller's orders, newest first.
         */
        get: operations["api_orders_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/checkout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an order from the current cart
         * @description Snapshots each cart item's current post price into the order, then empties the cart. The order is created with status='paid' (no real payment integration). Empty carts return 400.
         */
        post: operations["api_orders_checkout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve one of my orders
         * @description Owner only — 404 for other users' orders.
         */
        get: operations["api_orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/generate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request image generation
         * @description Validates the prompt + variants count + aspect ratio, creates a queued GenerationJob, and dispatches a Celery task that boto3-invokes the generate_image Lambda in us-west-2. Returns 202 with a polling URL. Rate-limited per user (see AI_RATE_LIMIT_PER_HOUR).
         */
        post: operations["api_ai_generate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/jobs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get generation job status
         * @description Returns the job state plus presigned GET URLs for the result PNGs once status is 'ready'. Owner-only.
         */
        get: operations["api_ai_jobs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/media/processed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lambda webhook: media processed
         * @description Called by the cut_image Lambda after a raw upload has been resized. Authentication: X-Lambda-Token header must match WEBHOOK_SHARED_SECRET.
         */
        post: operations["internal_media_processed_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `1:1` - 1:1
         *     * `4:5` - 4:5
         *     * `16:9` - 16:9
         * @enum {string}
         */
        AspectRatioEnum: "1:1" | "4:5" | "16:9";
        Cart: {
            readonly id: number;
            readonly items: components["schemas"]["CartItem"][];
            /** Format: decimal */
            readonly total: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        CartItem: {
            readonly id: number;
            readonly post_id: number;
            readonly qty: number;
            /** Format: decimal */
            readonly price: string;
            /** Format: double */
            readonly line_total: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        CartItemAddRequest: {
            post_id: number;
            /** @default 1 */
            qty: number;
        };
        CheckoutRequest: {
            payment_method: components["schemas"]["PaymentMethodEnum"];
            shipping_name: string;
            shipping_address: string;
            shipping_city: string;
            shipping_zip: string;
            /** @default  */
            shipping_country: string;
        };
        Error: {
            detail: string;
        };
        GenerationCreateRequest: {
            prompt: string;
            /** @default  */
            negative_prompt: string;
            variants_count: number;
            aspect_ratio: components["schemas"]["AspectRatioEnum"];
        };
        GenerationCreateResponse: {
            job_id: number;
            status_url: string;
        };
        GenerationJob: {
            readonly id: number;
            readonly prompt: string;
            readonly negative_prompt: string;
            readonly variants_count: number;
            readonly aspect_ratio: string;
            readonly status: components["schemas"]["GenerationJobStatusEnum"];
            readonly image_urls: string[];
            readonly error: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `queued` - Queued
         *     * `running` - Running
         *     * `ready` - Ready
         *     * `failed` - Failed
         * @enum {string}
         */
        GenerationJobStatusEnum: "queued" | "running" | "ready" | "failed";
        Health: {
            ok: boolean;
        };
        /**
         * @description * `post` - Post
         *     * `avatar` - Avatar
         * @enum {string}
         */
        KindEnum: "post" | "avatar";
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        MediaProcessedRequest: {
            s3_key: string;
            /** @default  */
            s3_key_resized: string;
            status: components["schemas"]["MediaProcessedStatusEnum"];
        };
        /**
         * @description * `ready` - ready
         *     * `failed` - failed
         * @enum {string}
         */
        MediaProcessedStatusEnum: "ready" | "failed";
        Order: {
            readonly id: number;
            readonly status: components["schemas"]["OrderStatusEnum"];
            /** Format: decimal */
            readonly total: string;
            payment_method: string;
            shipping_name: string;
            shipping_address: string;
            shipping_city: string;
            shipping_zip: string;
            shipping_country?: string;
            readonly items: components["schemas"]["OrderItem"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        OrderItem: {
            readonly id: number;
            readonly post_id: number;
            readonly qty: number;
            /** Format: decimal */
            readonly price_at_purchase: string;
            /** Format: double */
            readonly line_total: number;
        };
        /**
         * @description * `paid` - Paid
         *     * `shipped` - Shipped
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        OrderStatusEnum: "paid" | "shipped" | "cancelled";
        PaginatedOrderList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Order"][];
        };
        PaginatedPostList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Post"][];
        };
        PatchedCartItemUpdateRequest: {
            qty?: number;
        };
        PatchedPostRequest: {
            caption?: string;
            /** Format: decimal */
            price?: string | null;
        };
        PatchedUserUpdateRequest: {
            /** Format: email */
            email?: string;
        };
        /**
         * @description * `card` - card
         *     * `paypal` - paypal
         *     * `crypto` - crypto
         *     * `cod` - cod
         * @enum {string}
         */
        PaymentMethodEnum: "card" | "paypal" | "crypto" | "cod";
        Post: {
            readonly id: number;
            readonly owner_id: number;
            caption?: string;
            /** Format: decimal */
            price?: string | null;
            readonly status: components["schemas"]["PostStatusEnum"];
            readonly media: components["schemas"]["PostMedia"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        PostCreateRequest: {
            /** @default  */
            caption: string;
            /** Format: decimal */
            price?: string | null;
            media_ids: number[];
        };
        PostMedia: {
            readonly id: number;
            readonly kind: components["schemas"]["KindEnum"];
            readonly status: components["schemas"]["PostMediaStatusEnum"];
            readonly url: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `ready` - Ready
         *     * `failed` - Failed
         * @enum {string}
         */
        PostMediaStatusEnum: "pending" | "ready" | "failed";
        PostRequest: {
            caption?: string;
            /** Format: decimal */
            price?: string | null;
        };
        /**
         * @description * `draft` - Draft
         *     * `published` - Published
         * @enum {string}
         */
        PostStatusEnum: "draft" | "published";
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        UploadURLRequestRequest: {
            content_type: string;
            content_length: number;
            /** @default post */
            kind: components["schemas"]["KindEnum"];
        };
        UploadURLResponse: {
            media_id: number;
            /** Format: uri */
            upload_url: string;
            s3_key: string;
            expires_in: number;
        };
        User: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    api_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_users_posts_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPostList"];
                };
            };
        };
    };
    api_posts_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPostList"];
                };
            };
        };
    };
    api_posts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PostCreateRequest"];
                "multipart/form-data": components["schemas"]["PostCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_posts_upload_url_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadURLRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UploadURLRequestRequest"];
                "multipart/form-data": components["schemas"]["UploadURLRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadURLResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_posts_media_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostMedia"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_posts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_posts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PostRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PostRequest"];
                "multipart/form-data": components["schemas"]["PostRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
        };
    };
    api_posts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_posts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPostRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPostRequest"];
                "multipart/form-data": components["schemas"]["PatchedPostRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_cart_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_cart_items_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemAddRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CartItemAddRequest"];
                "multipart/form-data": components["schemas"]["CartItemAddRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartItem"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_cart_items_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_cart_items_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCartItemUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCartItemUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedCartItemUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartItem"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_orders_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOrderList"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_orders_checkout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckoutRequest"];
                "multipart/form-data": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_ai_generate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GenerationCreateRequest"];
                "multipart/form-data": components["schemas"]["GenerationCreateRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationCreateResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_ai_jobs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJob"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    internal_media_processed_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaProcessedRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MediaProcessedRequest"];
                "multipart/form-data": components["schemas"]["MediaProcessedRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
