# Generated by Django 6.0.5 on 2026-05-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='s3_key_raw',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
